let state = { chats: [], selected: null, polling: null };
async function fetchJSON(url, opts={}){ const res = await fetch(url, Object.assign({headers:{"Accept":"application/json"}}, opts)); if(!res.ok) throw new Error('HTTP '+res.status); return res.json(); }
function el(html){ const t = document.createElement('template'); t.innerHTML = html.trim(); return t.content.firstChild; }
async function loadChats(){ const q = document.getElementById('q').value.trim(); const status = document.getElementById('statusFilter').value; const data = await fetchJSON(`chat_api.php?action=list&q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`); state.chats = data.chats; renderList(); }
function renderList(){ const list = document.getElementById('chatList'); list.innerHTML = ''; if(state.chats.length === 0){ list.appendChild(el('<div class="placeholder" style="padding:12px;color:#6b7280;">No chats found.</div>')); return; } for(const c of state.chats){ const initials = (c.buyer_name||'U').trim().split(' ').map(s=>s[0]).join('').slice(0,2).toUpperCase(); const item = el(`<div class="item" data-id="${c.id}"><div class="avatar">${initials}</div><div class="meta"><div class="name">${escapeHtml(c.buyer_name||'(unknown)')} • <small>${escapeHtml(c.status)}</small></div><div class="subject">${escapeHtml(c.subject||'No subject')}${c.order_code? ' • ' + escapeHtml(c.order_code):''}</div></div><div class="time">${new Date(c.last_message_at || c.created_at).toLocaleString()}</div></div>`); item.addEventListener('click', ()=> selectChat(c.id)); list.appendChild(item);} }
function escapeHtml(s){return (s??'').replace(/[&<>"']/g, (m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
async function selectChat(id){ state.selected = id; document.getElementById('chatId').value = id; document.getElementById('messageInput').disabled = false; document.getElementById('sendBtn').disabled = false; const data = await fetchJSON(`chat_api.php?action=messages&chat_id=${id}`); const header = document.getElementById('threadTitle'); header.textContent = `${data.chat.buyer_name} — ${data.chat.subject || 'No subject'}`; const stSel = document.getElementById('threadStatus'); stSel.disabled = false; stSel.value = data.chat.status; stSel.onchange = async (e)=>{ await fetchJSON(`chat_api.php`, { method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'}, body: new URLSearchParams({action:'update_status', chat_id: id, status: e.target.value}).toString() }); loadChats(); }; const box = document.getElementById('messages'); box.innerHTML = ''; for(const m of data.messages){ const side = m.sender === 'admin' ? 'admin' : 'user'; const div = el(`<div class="msg ${side}"></div>`); div.textContent = m.message; const small = document.createElement('span'); small.className='when'; small.textContent=new Date(m.created_at).toLocaleString(); div.appendChild(small); box.appendChild(div); } box.scrollTop = box.scrollHeight; if(state.polling) clearInterval(state.polling); state.polling = setInterval(async ()=>{ if(!state.selected) return; const upd = await fetchJSON(`chat_api.php?action=messages&chat_id=${id}`); if(upd.messages.length !== data.messages.length){ await selectChat(id); } }, 4000); }
async function sendMessage(){ const chatId = document.getElementById('chatId').value; const text = document.getElementById('messageInput').value.trim(); if(!text) return; await fetchJSON('chat_api.php', { method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'}, body:new URLSearchParams({action:'send', chat_id:chatId, message:text}).toString() }); document.getElementById('messageInput').value=''; await selectChat(chatId); loadChats(); }
async function createChat(){ const buyer_name = prompt('Buyer name?'); if(!buyer_name) return; const buyer_email = prompt('Buyer email (optional)')||''; const subject = prompt('Subject (optional)')||''; const res = await fetchJSON('chat_api.php', { method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'}, body:new URLSearchParams({action:'create', buyer_name, buyer_email, subject}).toString() }); await loadChats(); await selectChat(res.chat_id); }
document.addEventListener('DOMContentLoaded', ()=>{ loadChats(); document.getElementById('q').addEventListener('input', ()=>{ clearTimeout(window.__t); window.__t=setTimeout(loadChats, 300); }); document.getElementById('statusFilter').addEventListener('change', loadChats); document.getElementById('sendBtn').addEventListener('click', sendMessage); document.getElementById('newChatBtn').addEventListener('click', createChat); });